### ISSUE TITLE
Can you add an example for Java - Junit - with Maven as well? 

### ISSUE THREAD

**Issue by PramodKumarYadav** [test-summary/examples#3]
The example contains Java - Junit with Ant. Since many use maven as a build system as well, could you add an example on how to make it work with maven structure? 

Note: I tried using this with maven but it did not work. I tried to get the path using "realpath "TEST-*.xml" in a step and got this. 
'/home/runner/work/zero/zero/TEST-*.xml'

But when I tried to use this path, here, it did not work. 

```
- name: Test Summary
      uses: test-summary/action@v1
      with:
        paths: "/home/runner/work/zero/zero/TEST-*.xml"
      if: always()
```

Also tried to get the absolute path of test summary and found this path: `/home/runner/work/zero/zero/test-summary.md` but it does not work. 

```
- name: Upload test summary
      uses: actions/upload-artifact@v3
      with:
        name: test-summary
        path: "/home/runner/work/zero/zero/test-summary.md"
      if: always()
```
![image](https://user-images.githubusercontent.com/11694972/169652027-802c54cb-65ed-4d9f-a304-eb91b7501387.png)
